/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.vink.example;

import dev.vink.example.config.AppConfig;
import dev.vink.example.resources.HealthCheckService;
import dev.vink.example.resources.PersonService;
import io.dropwizard.core.Application;
import io.dropwizard.core.setup.Environment;

public class App extends Application<AppConfig> {

    public static void main(String[] args) throws Exception {
        new App().run(args);
    }

    @Override
    public void run(AppConfig configuration, Environment environment) throws Exception {
        final PersonService personService = new PersonService();
        environment.jersey().register(personService);
        environment.healthChecks().register(getName(), new HealthCheckService());

    }

}
